
swagger: '2.0'
info:
  version: 1.0.0
  title: PDF to Word Conversion API
paths:
  /convert_word_to_pdf:
    post:
      operationId: convert_action.convert_word_to_pdf_file
      summary: Convert Word to Pdf
      consumes:
        - multipart/form-data
      parameters:
        - name: file
          in: formData
          type: file
          required: true
      responses:
        '200':
          description: Pdf file
        '400':
          description: Invalid input
        '500':
          description: Server error

  /convert_pdf_to_word:
    post:
      operationId: convert_action.convert_pdf_to_word_file
      summary: Convert Pdf to Word
      consumes:
        - multipart/form-data
      parameters:
        - name: file
          in: formData
          type: file
          required: true
      responses:
        '200':
          description: Word file
        '400':
          description: Invalid input
        '500':
          description: Server error
