
swagger: '2.0'
info:
  version: 1.0.0
  title: PDF to Word Conversion API
paths:
  /convert_word_to_pdf:
    post:
      operationId: convert_action.convert_word_to_pdf_file
      summary: Convert Word to Pdf
      consumes:
        - multipart/form-data
      parameters:
        - name: file
          in: formData
          type: file
          required: true
      responses:
        '200':
          description: Pdf file
        '400':
          description: Invalid input
        '500':
          description: Server error

  /convert_pdf_to_word:
    post:
      operationId: convert_action.convert_pdf_to_word_file
      summary: Convert Pdf to Word
      consumes:
        - multipart/form-data
      parameters:
        - name: file
          in: formData
          type: file
          required: true
      responses:
        '200':
          description: Word file
        '400':
          description: Invalid input
        '500':
          description: Server error

  /merge_pdfs:
    post:
      operationId: convert_action.merge_pdfs
      summary: Merge PDF Files
      consumes:
        - multipart/form-data
      parameters:
        - name: files
          in: formData
          type: array
          items:
            type: file
          required: true
          description: List of PDF files to merge
      responses:
        '200':
          description: Merged PDF file
        '400':
          description: Invalid input
        '500':
          description: Server error

  /get_pdf_pages:
    post:
      operationId: convert_action.get_pdf_pages
      summary: Get PDF Pages
      consumes:
        - multipart/form-data
      parameters:
        - name: file
          in: formData
          type: file
          required: true
          description: PDF file to get number of pages
      responses:
        '200':
          description: Number of pages in the PDF file
          schema:
            type: object
            properties:
              numPages:
                type: integer
        '400':
          description: Invalid input
        '500':
          description: Server error

  /split_pdf:
    post:
      operationId: convert_action.split_pdf
      summary: Split PDF File
      consumes:
        - multipart/form-data
      parameters:
        - name: file
          in: formData
          type: file
          required: true
          description: PDF file to be split
        - name: ranges
          in: formData
          type: string
          required: true
          description: JSON string of page ranges to split
      responses:
        '200':
          description: Split PDF files
        '400':
          description: Invalid input
        '500':
          description: Server error
